---
- name: Obtiene informacion VM
  hosts: localhost
  gather_facts: False
  vars:
    datacenter: JEAN
    ansible_python_interpreter: "/usr/bin/env python3"
  tasks:
    - name: Gather some info from a guest using the vSphere API output schema
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter }}"
        name: "{{ vm_name }}"
        schema: "vsphere"
        validate_certs: False
        #properties: ["config.hardware.memoryMB", "config.hardware.numCPU", "config.hardware.numCoresPerSocket", "config.datastoreUrl.name","confir.datastoreUrl.url","guest.disk", "config.files.vmPathName","guest.ipStack.hostName","guest.ipStack.ipAddress","guest.summary"]
        properties: ["config.hardware.memoryMB", "config.hardware.numCPU", "config.hardware.numCoresPerSocket", "guest.disk","guest.hostName","guest.ipStack"]
      delegate_to: localhost
      register: info
    - debug:
            msg: "{{ info }}"
