---
- name: get vm info detail
  hosts: localhost
  gather_facts: false
  vars:
    datacenter: JEAN
  tasks:
    - name: Gather a virtual machine info
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter }}"
        validate_certs: false
        name: "{{ vm_name }}"
        schema: vsphere
      register: gather_vm_info

    - name: Display the first interface set IP Address of a virtual machine
      debug:
        msg: "{{ gather_vm_info }}"
