---
- name: creacion de snapshot para VM - VMWARE
  hosts: localhost
  gather_facts: no
  vars:
    datacenter: JEAN
    ansible_playbook_interpreter: "/usr/bin/env python3"
  tasks:
    - name: Collecting disk information for given virtual machine from vCenter {{ vcenter_hostname }}
      vmware_guest_disk_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter }}"
        validate_certs: false
        name: "{{ vm_name }}"
      register: existing_disk

    - name: " Gather information from datacenter about specific datastore "
      vmware_datastore_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ item.value.backing_datastore }}"
      with_dict: "{{ existing_disk.guest_disk_info }}"
      register: ds_info
      no_log: true

    - name: debug exist disk
      debug:
        var:
          - existing_disk
          - ds_info

    - name: create "{{ vm_name }}" snapshot
      vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter }}"
        folder: "/{{ datacenter }}/vm/"
        name: "{{ vm_name }}"
        state: present
        snapshot_name: "{{ vm_name }}"
        description: "{{ vm_name }}_snapshot"
        validate_certs: False
      #loop: "{{ vm_name }}"
      delegate_to: localhost
      register: facts

    - name: use debug
      debug:
        var: facts
